In [ ]:
#to find find bank customer will leave the bank or not using ANN

In [1]:
#importing libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [8]:
print(tf.__version__)

2.3.0


In [10]:
#load dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [12]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [16]:
dataset.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [19]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [20]:
'''datapre processing tobe done on dataset
we can clearly visualize column 1,2,3,13 has no contribution ,so we will focus only on rest
of the columns'''



'datapre processing tobe done on dataset\nwe can clearly visualize column 1,2,3,13 has no contribution ,so we will focus only on rest\nof the columns'

In [59]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [60]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [61]:
print(y)

[1 0 1 ... 1 1 0]


In [62]:
#Taking care of missing data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 6:13])
x[:, 6:13] = imputer.transform(x[:, 6:13])

In [63]:
# Encoding the dependent Variable (gender)

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [65]:
# female encoded to 0 and male to 1
print(x)

[[619 'France' 0 ... 1.0 1.0 101348.88]
 [608 'Spain' 0 ... 0.0 1.0 112542.58]
 [502 'France' 0 ... 1.0 0.0 113931.57]
 ...
 [709 'France' 0 ... 0.0 1.0 42085.58]
 [772 'Germany' 1 ... 1.0 0.0 92888.52]
 [792 'France' 0 ... 1.0 0.0 38190.78]]


In [66]:
#one hot encoding in geography colomun (independent variable)

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [68]:
print(x)

[[1.0 0.0 0.0 ... 1.0 1.0 101348.88]
 [0.0 0.0 1.0 ... 0.0 1.0 112542.58]
 [1.0 0.0 0.0 ... 1.0 0.0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0.0 1.0 42085.58]
 [0.0 1.0 0.0 ... 1.0 0.0 92888.52]
 [1.0 0.0 0.0 ... 1.0 0.0 38190.78]]


In [69]:
#split train and test

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [71]:
#feature scaling(compulsary in deep learning)

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [73]:
#part2 buid ANN model

In [74]:
#initaize ann

In [75]:
ann=tf.keras.models.Sequential()

In [76]:
#ADDING i/p and 1st layers

In [77]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [78]:
#adding 2nd hidden layers

In [79]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [80]:
#adding O/P layer

In [81]:
#ann.add(tf.keras.layers.Dense(units=1,activation="softmax")) for non-binary classification
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [82]:
#part3 training ann

In [83]:
#compile ann

In [84]:
#ann.compile(optimizer='adam',loss='category_crossentropy',metrics=['accuracy'] for non-binary classifiacation problems)
#adam is used to run stochastic gradient descent
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [85]:
#training ann on training set

In [86]:
ann.fit(X_train,y_train , batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6826 - accuracy: 0.6277
Epoch 2/100
250/250 [==============================] - 0s 519us/step - loss: 0.5360 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 534us/step - loss: 0.4562 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 496us/step - loss: 0.4354 - accuracy: 0.7995
Epoch 5/100
250/250 [==============================] - 0s 521us/step - loss: 0.4246 - accuracy: 0.8089
Epoch 6/100
250/250 [==============================] - 0s 486us/step - loss: 0.4182 - accuracy: 0.8164
Epoch 7/100
250/250 [==============================] - 0s 496us/step - loss: 0.4107 - accuracy: 0.8200
Epoch 8/100
250/250 [==============================] - 0s 510us/step - loss: 0.3999 - accuracy: 0.8275
Epoch 9/100
250/250 [==============================] - 0s 499us/step - loss: 0.3849 - accuracy: 0.8404
Epoch 10/100
250/250 [==============================] - 0s 539us/step - los

250/250 [==============================] - 0s 521us/step - loss: 0.3357 - accuracy: 0.8622
Epoch 80/100
250/250 [==============================] - 0s 526us/step - loss: 0.3352 - accuracy: 0.8626
Epoch 81/100
250/250 [==============================] - 0s 493us/step - loss: 0.3353 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 497us/step - loss: 0.3351 - accuracy: 0.8624
Epoch 83/100
250/250 [==============================] - 0s 539us/step - loss: 0.3355 - accuracy: 0.8639
Epoch 84/100
250/250 [==============================] - 0s 503us/step - loss: 0.3351 - accuracy: 0.8648
Epoch 85/100
250/250 [==============================] - 0s 506us/step - loss: 0.3352 - accuracy: 0.8626
Epoch 86/100
250/250 [==============================] - 0s 520us/step - loss: 0.3351 - accuracy: 0.8621
Epoch 87/100
250/250 [==============================] - 0s 511us/step - loss: 0.3346 - accuracy: 0.8639
Epoch 88/100
250/250 [==============================] - 0s 504us/step - loss:

In [95]:
'''we have to predict if customer with data as follow will leave
the bank or not.---------Geography :france ,Gender: male , Age:40 , Tenure3 years , Balance:$60000 , NumOfProducts: 2 , HasCrCard:yes , IsActiveMember: yes , 
EstimatedSalary: $50000 , Exited :(if customer will exit the bank(1 for yes , 0 for no) ?)'''
#predict(should be 2 d arry) ,1.0.0 is encoded value of france,1 is for male

'we have to predict if customer with data as follow will leave\nthe bank or not.---------Geography :france ,Gender: male , Age:40 , Tenure3 years , Balance:$60000 , NumOfProducts: 2 , HasCrCard:yes , IsActiveMember: yes , \nEstimatedSalary: $50000 , Exited :(if customer will exit the bank(1 for yes , 0 for no) ?)'

In [92]:
'''check if some scaling was applied during training stage,yes we did applied so we will same for 
single observation which we will use for prediction,we will use sc object for the same''' 

'check if some scaling was applied during training stage,yes we did applied so we will same for \nsingle observation which we will use for prediction,we will use sc function for the same'

In [ ]:
#sigmoid function will return probablity ,so we can transform it as below

In [94]:
if (ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>.5):
    print("50% chance that customer will leave")
else :
    print("customer will not leave bank ,CONGO!!")

customer will not leave bank ,CONGO!!


In [96]:
#predict the test set

In [98]:
y_pred = ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [100]:
'''generate confusion matrix and final accuracy of prediction if customer will 
stays in the bank or will leave the bank'''

'generate confusion matrix and final accuracy of prediction if customer will \nstays in the bank or will leave the bank'

In [101]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 199  206]]


0.8675